'use client';

import { useState } from 'react';
import { Locale, Category } from '@/types';
import { CITIES_AREAS, CATEGORIES } from '@/lib/constants';

interface Props { locale: Locale }
export default function SubmitChapterClient({ locale }: Props) {
  const [name, setName] = useState(''); const [city, setCity] = useState(''); const [area, setArea] = useState(''); const [categories, setCategories] = useState<Category[]>([]); const [contact, setContact] = useState(''); const [description, setDescription] = useState(''); const [confirmed, setConfirmed] = useState(false); const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const hi = locale === 'hi'; const areas = CITIES_AREAS.find((item) => item.city === city)?.areas || [];
  function toggle(category: Category) { setCategories((items) => items.includes(category) ? items.filter((item) => item !== category) : [...items, category]); }
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || !city || !area || !categories.length || !contact.trim() || !confirmed || status === 'loading') return; setStatus('loading'); try { const response = await fetch('/api/chapters', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: name.trim(), city, area, categories, contact_method: contact.trim(), description: description.trim() }) }); if (!response.ok) throw new Error('failed'); setStatus('success'); } catch { setStatus('error'); } }
  if (status === 'success') return <section className="success-state" role="status"><p className="success-mark" aria-hidden="true">✓</p><h2>{hi ? 'समूह समीक्षा के लिए भेजा गया' : 'Group sent for review'}</h2><p>{hi ? 'यह अभी सार्वजनिक नहीं है। मॉडरेटर के स्वीकृत करने के बाद यह निर्देशिका में दिखेगा।' : 'It is not public yet. It will appear in the directory if a moderator approves it.'}</p><a href="/directory" className="brutal-btn brutal-btn-primary">{hi ? 'निर्देशिका पर जाएँ' : 'Go to directory'}</a></section>;
  return <form onSubmit={submit} className="civic-form">
    <fieldset><legend>{hi ? '1. समूह की पहचान' : '1. Identify the group'}</legend><label htmlFor="group-name" className="field-label">{hi ? 'समूह का सार्वजनिक नाम' : 'Public group name'}</label><input id="group-name" value={name} onChange={(event) => setName(event.target.value)} required maxLength={120} className="brutal-input" /></fieldset>
    <fieldset><legend>{hi ? '2. सामान्य स्थान' : '2. General location'}</legend><p className="field-help">{hi ? 'निजी पता न दें।' : 'Do not enter a private address.'}</p><div className="filter-grid"><label><span>{hi ? 'शहर' : 'City'}</span><select value={city} onChange={(event) => { setCity(event.target.value); setArea(''); }} required className="brutal-select"><option value="">{hi ? 'शहर चुनें' : 'Choose city'}</option>{CITIES_AREAS.map((item) => <option key={item.city}>{item.city}</option>)}</select></label><label><span>{hi ? 'क्षेत्र' : 'Area'}</span><select value={area} onChange={(event) => setArea(event.target.value)} required disabled={!city} className="brutal-select"><option value="">{hi ? 'क्षेत्र चुनें' : 'Choose area'}</option>{areas.map((item) => <option key={item}>{item}</option>)}</select></label></div></fieldset>
    <fieldset><legend>{hi ? '3. समूह क्या करता है?' : '3. What does the group do?'}</legend><p className="field-help">{hi ? 'सभी लागू सेवाएँ चुनें।' : 'Choose every service that applies.'}</p><div className="checkbox-card-grid">{CATEGORIES.map((category) => <label key={category.value} className={`check-card ${categories.includes(category.value) ? 'selected' : ''}`}><input type="checkbox" checked={categories.includes(category.value)} onChange={() => toggle(category.value)} /><span>{hi ? category.labelHi : category.labelEn}</span></label>)}</div></fieldset>
    <fieldset><legend>{hi ? '4. सार्वजनिक संपर्क' : '4. Public contact'}</legend><label htmlFor="group-contact" className="field-label">{hi ? 'वेबसाइट, समूह ईमेल या सार्वजनिक फ़ॉर्म' : 'Website, group email, or public form'}</label><input id="group-contact" value={contact} onChange={(event) => setContact(event.target.value)} required maxLength={300} className="brutal-input" placeholder="https://…" /><p className="field-help">{hi ? 'यह सबको दिखेगा। व्यक्तिगत फोन, निजी ईमेल या किसी बच्चे का संपर्क न दें।' : 'Everyone will see this. Do not use a personal phone, private email, or a child’s contact.'}</p></fieldset>
    <fieldset><legend>{hi ? '5. समूह का छोटा परिचय' : '5. Short group description'}</legend><label htmlFor="group-description" className="field-label">{hi ? 'यह कैसे मदद करता है?' : 'How does it help?'}</label><textarea id="group-description" value={description} onChange={(event) => setDescription(event.target.value.slice(0, 500))} maxLength={500} rows={4} className="brutal-textarea" /><div className="field-footer"><span>{hi ? 'लोगों के नाम या निजी जानकारी न दें।' : 'Do not include people’s names or private details.'}</span><span>{description.length}/500</span></div></fieldset>
    <section className="review-panel" aria-labelledby="group-review-title"><h2 id="group-review-title">{hi ? 'भेजने से पहले जाँचें' : 'Check before sending'}</h2><p>{hi ? 'स्वीकृति के बाद ऊपर की सारी जानकारी सार्वजनिक होगी। लिस्टिंग की समीक्षा होती है, लेकिन यह समूह की कानूनी या सुरक्षा जाँच नहीं है।' : 'After approval, everything above becomes public. Listings are reviewed, but this is not a legal or safety certification of the group.'}</p><label className="check-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} required /><span>{hi ? 'मुझे यह सार्वजनिक संपर्क साझा करने की अनुमति है। मैं 18+ हूँ और जानकारी सही है।' : 'I have permission to share this public contact. I am 18+ and the information is accurate.'}</span></label></section>
    {status === 'error' && <p className="error-message" role="alert">{hi ? 'समूह नहीं भेजा गया। अपना कनेक्शन देखें और फिर कोशिश करें।' : 'The group was not sent. Check your connection and try again.'}</p>}<button type="submit" disabled={status === 'loading' || !confirmed} className="brutal-btn brutal-btn-primary brutal-btn-lg form-primary-action">{status === 'loading' ? (hi ? 'समीक्षा के लिए भेज रहे हैं…' : 'Sending for review…') : (hi ? 'समीक्षा के लिए भेजें' : 'Send for review')}</button>
  </form>;
}
