'use client';

import { useCallback, useState } from 'react';
import { Locale, Category, PostType, Urgency } from '@/types';
import { CITIES_AREAS, CATEGORIES, MAX_DESCRIPTION_LENGTH } from '@/lib/constants';
import ProofOfWork from '@/components/ProofOfWork';

interface Props { locale: Locale }
type Status = 'idle' | 'loading' | 'success' | 'error' | 'rate-limited' | 'pii-blocked';

export default function CreatePostClient({ locale }: Props) {
  const [powSolved, setPowSolved] = useState(false); const [challenge, setChallenge] = useState(''); const [nonce, setNonce] = useState(0); const [powAttempt, setPowAttempt] = useState(0);
  const [type, setType] = useState<PostType>('need'); const [category, setCategory] = useState<Category | ''>(''); const [city, setCity] = useState(''); const [area, setArea] = useState(''); const [urgency, setUrgency] = useState<Urgency>('routine'); const [description, setDescription] = useState(''); const [confirmed, setConfirmed] = useState(false); const [status, setStatus] = useState<Status>('idle'); const [error, setError] = useState('');
  const hi = locale === 'hi'; const areas = CITIES_AREAS.find((item) => item.city === city)?.areas || [];
  const onSolved = useCallback((value: string, number: number) => { setChallenge(value); setNonce(number); setPowSolved(true); }, []);
  function resetProofOfWork() { setPowSolved(false); setChallenge(''); setNonce(0); setPowAttempt((value) => value + 1); }

  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!category || !city || !area || !description.trim() || !confirmed || status === 'loading') return; setStatus('loading'); setError('');
    try {
      const response = await fetch('/api/posts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, category, city, area, urgency, description: description.trim(), pow_challenge: challenge, pow_nonce: nonce }) });
      if (response.status === 429) { resetProofOfWork(); return setStatus('rate-limited'); }
      if (response.status === 422) { const data = await response.json(); setError(data.error || ''); return setStatus('pii-blocked'); }
      if (!response.ok) throw new Error('failed'); setStatus('success');
    } catch { resetProofOfWork(); setStatus('error'); }
  }

  if (status === 'success') return <section className="success-state" role="status"><p className="success-mark" aria-hidden="true">✓</p><h2>{hi ? 'पोस्ट समीक्षा के लिए भेजी गई' : 'Post sent for review'}</h2><p>{hi ? 'यह अभी सार्वजनिक नहीं है। मॉडरेटर के स्वीकृत करने के बाद यह बोर्ड पर दिखेगी।' : 'It is not public yet. It will appear on the board if a moderator approves it.'}</p><a href="/my-posts" className="brutal-btn brutal-btn-primary">{hi ? 'मेरी पोस्ट देखें' : 'View my posts'}</a></section>;

  return <ProofOfWork key={powAttempt} locale={locale} onSolved={onSolved}>{powSolved && <form onSubmit={submit} className="civic-form">
    <fieldset><legend>{hi ? '1. आप क्या करना चाहते हैं?' : '1. What do you want to do?'}</legend><div className="radio-card-grid"><label className={`radio-card ${type === 'need' ? 'selected' : ''}`}><input type="radio" name="type" checked={type === 'need'} onChange={() => setType('need')} /><span><strong>{hi ? 'मदद पाएँ' : 'Get help'}</strong><small>{hi ? 'मुझे किसी चीज़ की जरूरत है' : 'I need something'}</small></span></label><label className={`radio-card ${type === 'offer' ? 'selected' : ''}`}><input type="radio" name="type" checked={type === 'offer'} onChange={() => setType('offer')} /><span><strong>{hi ? 'मदद दें' : 'Offer help'}</strong><small>{hi ? 'मैं कुछ दे या कर सकता/सकती हूँ' : 'I can give or do something'}</small></span></label></div></fieldset>
    <fieldset><legend>{hi ? '2. किस तरह की मदद?' : '2. What kind of help?'}</legend><label htmlFor="post-category" className="field-label">{hi ? 'श्रेणी' : 'Category'}</label><select id="post-category" value={category} onChange={(event) => setCategory(event.target.value as Category)} required className="brutal-select"><option value="">{hi ? 'एक चुनें' : 'Choose one'}</option>{CATEGORIES.map((item) => <option key={item.value} value={item.value}>{hi ? item.labelHi : item.labelEn}</option>)}</select></fieldset>
    <fieldset><legend>{hi ? '3. कौन सा सामान्य स्थान?' : '3. What general location?'}</legend><p className="field-help">{hi ? 'सटीक पता न दें।' : 'Do not give an exact address.'}</p><div className="filter-grid"><label><span>{hi ? 'शहर' : 'City'}</span><select value={city} onChange={(event) => { setCity(event.target.value); setArea(''); }} required className="brutal-select"><option value="">{hi ? 'शहर चुनें' : 'Choose city'}</option>{CITIES_AREAS.map((item) => <option key={item.city}>{item.city}</option>)}</select></label><label><span>{hi ? 'क्षेत्र' : 'Area'}</span><select value={area} onChange={(event) => setArea(event.target.value)} required disabled={!city} className="brutal-select"><option value="">{hi ? 'क्षेत्र चुनें' : 'Choose area'}</option>{areas.map((item) => <option key={item}>{item}</option>)}</select></label></div></fieldset>
    <fieldset><legend>{hi ? '4. इसमें कितनी जल्दी है?' : '4. How soon is it needed?'}</legend><div className="radio-card-grid"><label className={`radio-card ${urgency === 'routine' ? 'selected' : ''}`}><input type="radio" name="urgency" checked={urgency === 'routine'} onChange={() => setUrgency('routine')} /><span><strong>{hi ? 'सामान्य' : 'Not immediate'}</strong><small>{hi ? 'कुछ समय इंतज़ार हो सकता है' : 'It can wait a while'}</small></span></label><label className={`radio-card ${urgency === 'urgent' ? 'selected' : ''}`}><input type="radio" name="urgency" checked={urgency === 'urgent'} onChange={() => setUrgency('urgent')} /><span><strong>{hi ? 'समय-संवेदनशील' : 'Time-sensitive'}</strong><small>{hi ? 'जल्द मदद चाहिए, पर यह आपातकाल नहीं है' : 'Help is needed soon, but this is not an emergency'}</small></span></label></div>{urgency === 'urgent' && <div className="warning-panel"><strong>{hi ? 'तुरंत खतरा है?' : 'In immediate danger?'}</strong><p>{hi ? 'यह साइट आपातकालीन सेवा नहीं है। स्थानीय आपातकालीन सेवा या भरोसेमंद वयस्क से अभी संपर्क करें।' : 'This site is not an emergency service. Contact local emergency services or a trusted adult now.'}</p></div>}</fieldset>
    <fieldset><legend>{hi ? '5. छोटी जानकारी दें' : '5. Add a short description'}</legend><label htmlFor="post-description" className="field-label">{hi ? 'क्या चाहिए या क्या दे सकते हैं?' : 'What do you need or offer?'}</label><textarea id="post-description" value={description} onChange={(event) => setDescription(event.target.value.slice(0, MAX_DESCRIPTION_LENGTH))} maxLength={MAX_DESCRIPTION_LENGTH} required rows={5} className="brutal-textarea" placeholder={hi ? 'उदाहरण: इस क्षेत्र में आज रात दो लोगों के लिए भोजन चाहिए।' : 'Example: Need dinner for two people in this area tonight.'} /><div className="field-footer"><span>{hi ? 'नाम, फोन, पहचान संख्या या सटीक पता न लिखें।' : 'No names, phone numbers, ID numbers, or exact addresses.'}</span><span>{description.length}/{MAX_DESCRIPTION_LENGTH}</span></div></fieldset>
    <section className="review-panel" aria-labelledby="review-title"><h2 id="review-title">{hi ? 'भेजने से पहले जाँचें' : 'Check before sending'}</h2><ul className="plain-list"><li>{hi ? 'स्वीकृति के बाद विवरण, शहर और क्षेत्र सार्वजनिक होंगे।' : 'After approval, the description, city, and area will be public.'}</li><li>{hi ? 'जवाब देने वाले की पहचान सत्यापित नहीं है।' : 'Responders are not identity-verified.'}</li><li>{hi ? 'पोस्ट 72 घंटे बाद बोर्ड पर दिखना बंद कर देगी।' : 'The post stops showing on the board after 72 hours.'}</li></ul><label className="check-row"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} required /><span>{hi ? 'मैंने निजी जानकारी हटा दी है। मैं 18+ हूँ या भरोसेमंद वयस्क के साथ यह पोस्ट बना रहा/रही हूँ।' : 'I removed private details. I am 18+ or I am making this post with a trusted adult.'}</span></label></section>
    {status === 'error' && <p className="error-message" role="alert">{hi ? 'पोस्ट नहीं भेजी गई। अपना कनेक्शन देखें और फिर कोशिश करें।' : 'The post was not sent. Check your connection and try again.'}</p>}{status === 'rate-limited' && <p className="error-message" role="alert">{hi ? 'अभी और पोस्ट नहीं भेज सकते। कुछ समय बाद फिर कोशिश करें।' : 'You cannot send another post yet. Wait and try again later.'}</p>}{status === 'pii-blocked' && <div className="error-message" role="alert"><strong>{hi ? 'निजी जानकारी हटाएँ।' : 'Remove private information.'}</strong><p>{error || (hi ? 'फोन, पहचान संख्या, पूरा नाम या सटीक पता हटाएँ।' : 'Remove phone numbers, ID numbers, full names, or exact addresses.')}</p></div>}
    <button type="submit" disabled={status === 'loading' || !confirmed} className="brutal-btn brutal-btn-primary brutal-btn-lg form-primary-action">{status === 'loading' ? (hi ? 'समीक्षा के लिए भेज रहे हैं…' : 'Sending for review…') : (hi ? 'समीक्षा के लिए भेजें' : 'Send for review')}</button>
  </form>}</ProofOfWork>;
}
